version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: user_mgmt_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: userapp
      POSTGRES_PASSWORD: userapp123
      POSTGRES_DB: user_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userapp -d user_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: user_mgmt_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    driver: local





